file(READ "${VER_SRC}" VER)
string(STRIP "${VER}" VER)
set(CONTENT "#pragma once\n#define WINIX_VERSION \"${VER}\"\n")
if(EXISTS "${VER_DST}")
    file(READ "${VER_DST}" OLD)
    if(OLD STREQUAL CONTENT)
        return()
    endif()
endif()
file(WRITE "${VER_DST}" "${CONTENT}")
